# Generated by Django 5.1 on 2024-09-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media/profile_images"
            ),
        ),
    ]
