# Generated by Django 5.1 on 2024-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Birthday"),
        ),
    ]
