# Generated by Django 5.1 on 2024-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_notes_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
