version: '3.7'

x-backend-service: &x-backend-service
  image: denys1608/personal-assistant:latest
  env_file:
    - .env
  restart: unless-stopped
  labels:
    - "com.centurylinklabs.watchtower.enable=true"

services:

  migrate:
    <<: *x-backend-service
    command: python manage.py migrate --noinput && python manage.py seeds
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - assets_volume:/app/assets
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: [ "gunicorn", "-c", "/app/config/gunicorn.py", "config.wsgi" ]

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - assets_volume:/assets
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped



  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.lifecycle.post-update=./bin/restart_all.sh"


volumes:
  postgres_data:
  static_volume:
  assets_volume:
  redis_data:
