# Generated by Django 5.1 on 2024-08-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 27, 13, 43, 14, 826858)
            ),
        ),
    ]
