# Generated by Django 5.1 on 2024-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_users_name_alter_notes_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
